export enum actionTypes {
    CREATE_NEW_ROW_AT_POSITION = "CREATE_NEW_ROW_AT_POSITION",
    CREATE_NEW_COLUMN_AT_POSTITION = "CREATE_NEW_COLUMN_AT_POSTITION",
    DELETE_ROW_BY_INDEX = "DELETE_ROW_BY_INDEX",
    DELETE_COLUMN_BY_INDEX = "DELETE_COLUMN_BY_INDEX",
    CHANGE_CELL_VALUE = "CHANGE_CELL_VALUE",
}